
---
format:
  html: {toc: true, toc-depth: 4, theme: cosmo, output-file: index.html}
code-block-background: true

---
<style></style><style>.printedClojure .sourceCode {
  background-color: transparent;
  border-style: none;
}
</style><style>.clay-limit-image-width .clay-image {max-width: 100%}
.clay-side-by-side .sourceCode {margin: 0}
.clay-side-by-side {margin: 1em 0}
</style>
<script src="index_files/md-default0.js" type="text/javascript"></script><script src="index_files/md-default1.js" type="text/javascript"></script>

::: {.sourceClojure}
```clojure
(ns index
  "Entrypoint for the Clay-generated docs -> docs/generated/index.html"
  (:require
    [scicloj.kindly.v4.kind :as kind]
    [scicloj.kindly.v4.api :as kindly]))
```
:::


# Concept


-   build a HD/VSA framework for wolfram + wolframite

-   Inspirations:

    -   <https://torchhd.readthedocs.io/en/stable/>
    -   <https://www.hd-computing.com/software>

-   Re-cook HD/VSA papers;

    -   <https://github.com/IBM/neuro-vector-symbolic-architectures-raven>
    -   (integrate with existing neural net framework of wolfram)

-   Apply the approach and investige architectures / parameters etc. to

    -   arc-AGI (filter a 3x3 dataset?)
    -   copycat domain

-   Attempt to model \'analogical reasoning\' (see existing Lit)

## Mushroom body models?

-   make a HD version of mushrooom body models, compare to sparse
    distrubute memory, modern hopfield and transformer architectures

-   try those also as analogical reasoners

# Implementations

-   HD/VSA: MAP, block sparse, ...
-   resonator networks
-   Sparse Distrubuted Memory


# Build Docs

- Depends on a Quarto install

# Dev

setup clay on save: 


```
(defun my-setup-clay-save-hook ()
  (interactive)
  (add-hook
   'after-save-hook
   (defun my-clay-reload  ()
     (interactive)
     (cider-sync-tooling-eval
      (format "((requiring-resolve 'scicloj.clay.v2.api/make!)\n {:source-path \"%s\"})"
              (buffer-file-name))))
   nil
   t))
```



## Further documentation
See the book content menu on the left side


```{=html}
<div style="background-color:grey;height:2px;width:100%;"></div>
```



```{=html}
<div><pre><small><small>source: notebooks/index.clj</small></small></pre></div>
```
